version: '3.8'
services:
  backend:
    build: .
    container_name: leaf-lense-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./model:/app/model
    depends_on:
      - db
  frontend:
    build: ./frontend
    container_name: leaf-lense-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
  db:
    image: postgres:15
    container_name: leaf-lense-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
